### ISSUE TITLE
ShapefileImporter WKT

### ISSUE THREAD

**Issue by evandroberto** [neo4j-contrib/spatial#230] opened 2016-04-18 14:24 UTC
When I use the shapefileimporter class, my data looks like this:
![import-java](https://cloud.githubusercontent.com/assets/12130242/14607120/a72628d0-0556-11e6-961a-206a8d85f651.png)
What kind of format is the wkt property? 
Is it supposed to be that way? 
How can I visualize it in a map?

I'm currently using a python script to import data from a csv file created from the shapefile, but it takes quite some time compared to the java class. The data using the script looks like this, which I can work fine in a map, but I would like to use the faster and "official" approach.
![import-python](https://cloud.githubusercontent.com/assets/12130242/14607284/5419ae18-0557-11e6-99da-ccbbcbf67a90.png)

**Comment by ehx-v1** [comment] 2016-04-19 10:52
perhaps the same multipolygon coords mapped to a different scale or projection?

**Comment by evandroberto** [comment] 2016-04-20 19:12
But shouldn't it be WKT? This is just a huge array of numbers.

**Comment by craigtaverner** [comment] 2016-04-23 10:23
I'm curious how you rendered the first data as JSON? Was this a node in the database and you have a serializer to generate JSON? My guess is that the 'wkt' field is actually 'wkb' (well known binary) which is a binary version of WKT. And so what you are seeing is a byte[] rendered into a JSON array of numbers. The fact that no number exceeds the bounds of a signed byte does support this hypothesis.

If my guess is right, then the only bug is that the field should have been called 'wkb' instead of 'wkt'. I've reviewed the code and see that in fact both the WKTGeometryEncoder and the WKBGeometryEncoder classes share most of the same code, including the default choice of property name 'wkt'. I would suggest we make that default be something like 'geometry' perhaps, and not suggest an encoding in the property name.

If you used Neo4j Spatial to make this node, and use it to also read it back into a Geometry object, then the WKB will be interpreted as WKB correctly, regardless of the property name used.

So, for your case I would recommend you use the WKTGeometryEncoder, if you specifically would like to be able to see the Geometry information in the property. If all you want is to be able to read it back, make sure to use the layer methods to read the node. If you find the node using non-spatial methods, you should still use the layer to get the GeometryEncoder to decode the node for you using something like:

```
Geometry geometry = layer.getGeometryEncoder().decodeGeometry(node);
```

**Comment by evandroberto** [comment] 2016-04-27 01:14
I used the REST API to get the data in both cases.

I imported the same shapefile using PostGIS and the geometry stored in my relational table as WKB looks like this:
"0106000000020000000103000000010000009A1B0000122D3B8280A747C04A81B0EE150930C05A9EB311CDA747C01E3F1390750A30C04E1BB56271A747C03ECC1445A90A30C0B118858 (...)"
Which does kinda look like the beginning of the first array. Not sure about the rest, though.

I'll try your suggestions and see what happens.

**Comment by ehx-v1** [comment] 2016-05-19 13:24
After a look into the code I found out that the ShapefileImporter does use the WKBGeometryEncoder, so the identification as WKB is confirmed I think.

**Comment by ehx-v1** [comment] 2016-05-31 09:16
By now I have a question about the WKT too: From what I found out, the official WKT standard is like `POINT (x y)`, i.e. `POINT (lon lat)`, but many geospatial applications deviate from this, using it like `POINT (lat lon)`. So how is this about Spatial?

**Comment by craigtaverner** [comment] 2016-05-31 10:04
The order is always `lon lat` in Neo4j Spatial with one unfortunate exception, the withinDistance() query to the IndexProvider has two forms, one using lat,lon the other using lon,lat. This is an unfortunate mistake, as both should use lon,lat.

For completeness, this is what I found about the two versions of withinDistance():

* withinDistance('[lng,lat,distanceInKm]')
  * expects params to be a string parsable as JSON array of longitude, latitude and distance
* withinDistance(point=[lat,lng],distanceInKm=...)
  * expects params to be named map with point being a literal list of doubles with latitude before longitude (just to keep us confused!), and distanceInKm to be a literal double

Unfortunately it seems the second, confusing form, is the one most commonly used. In our Neo4j 3.0 version we are deprecating the IndexProvider, and have made instead a bunch of cypher procedures to give access to the Spatial library from Cypher, so this problem will go away.

**Comment by ehx-v1** [comment] 2016-05-31 11:06
I would expect this to result from that the point the second withinDistance version uses does not come from JTS but from a different geospatial library instead, and that this library uses the ISO standard which says lat first, while JTS sticks with WKT-styled lon first.

**Comment by ehx-v1** [comment] 2016-05-31 11:07
But what you said especially means that for where I need it the stored data is treated as lon first. So thanks, I know all I need.

**Comment by ehx-v1** [comment] 2016-06-01 07:01
BTW I figured out that the lat first library is probably Lucene 6.0. We had a short presentation in our department lately, where it was pointed out that Lucene moved from lon first to lat first between releases. (This makes the data handling change, but the method signature stayed the same, as both are double type, so the compiler won't notice the change which therefore will subtlely screw up some applications. But what matters for this disccussion is that lucene 6.0 is lat first.) A fix might be moving back to Lucene 5.5.0, which was lon first.

**Comment by craigtaverner** [comment] 2016-06-01 07:49
On a related note, I should mention that the new built-in point() function in Neo4j 3.0 (not the spatial library, but Neo4j itself) actually gets around this issue by insisting on named parameters (actually a map). So you need to say, for example `p=point({latitude:12.3, longitude:32.1})`. Then the order issue goes away.

**Comment by craigtaverner** [comment] 2016-06-01 07:53
We have not heard back from @evandroberto in over a month, so I'm going to assume his original issue is resolved and close this issue.

**Closed by craigtaverner** 2016-06-01 07:53 UTC

**Comment by mariocuellar12** [comment] 2016-06-07 05:20
SIMPLY IS CHANGE IN THE CODE:

**Comment by mariocuellar12** [comment] 2016-06-07 05:23
CHANGE IS SIMPLY THE HIGHLIGHT IN THE CODE:
![wkt](https://cloud.githubusercontent.com/assets/19672501/15846763/c74bf304-2c45-11e6-8c02-c5a33e02b198.PNG)

FOR:
"WKT"

 I HOPE YOU OPERATE

**Comment by ehx-v1** [comment] 2016-06-07 12:09
Did you read the discussion at all? The WKTGeometryEncoder will never be used in the ShapefileImporter, and the property name has already changed to "geometry", and the issue is solved! What exactly is your problem?

**Comment by craigtaverner** [comment] 2016-06-07 21:17
Let's not get into any arguments here. Everyone is entitled to their opinion. My opinion is that:

* @evandroberto has not replied since the original suggestion, and so we can assume this issue closed and the change to 'geometry' for the property name is sufficient for him.
* If @mariocuellar12 would prefer a different solution, perhaps a configurable option for ShapefileImporter to select between WKT and WKB, I would suggest he open a new issue with a request for such an option.

**Comment by ehx-v1** [comment] 2016-06-23 06:45
Sorry, I thought @mariocuellar12 had misunderstood the whole issue and proposed a fix. That's why I said a completely different fix is already done. The default will stay WKBGeometryEncoder. Also, I'd still appreciate some clarification about what @mariocuellar12 is actually asking for - and about why he's writing in caps.

**Comment by craigtaverner** [comment] 2016-06-23 13:56
I agree that @mariocuellar12 was not very clear in his request. I think he was requesting that the default encoder for shapefile importing be changed to WKT. But that is a different suggestion than this issue really deals with, which is why I recommended he create a new issue requesting that with a little more motivation. For now this issue can remain closed.

**Comment by ehx-v1** [comment] 2016-06-24 07:32
I agree. However I kind of still have the impression that @mariocuellar12 simply misunderstood the issue. One fact that would back this up is that at the top of his screenshot, you can see a path, and this path contains something in Spanish or similar. I guess he just had some language problems. His wording would also imply that he's far from being a native speaker. (Not meant to be offending.)
