### ISSUE TITLE
osmimporter not creating R-Tree index for points/linestrings for osm files downloaded from geofabrik (montenegro+scotland)

### ISSUE THREAD

**Issue by 100beans** [neo4j-contrib/spatial#347] opened 2018-07-16 05:53 UTC

**Comment by 100beans** [comment] 2018-07-16 05:57
At the end of the import I just receive:

"Index[0]: info | Re-indexing elapsed time in seconds: 0.033
Geometry statistics for 0 geometry types:"

thus can't run any spatial procedures as no geometries are indexed

**Comment by craigtaverner** [comment] 2018-07-22 09:35
Could you describe which version of Neo4j and Neo4j Spatial you are using, and perhaps attach, or provide a URI for an example OSM file that has this problem, so I can try reproduce it?

**Comment by Kubera2017** [comment] 2018-08-02 20:55
@craigtaverner pls don't take into account my previous logs - I don't know that your procedure adds only nodes attached to ways. I tried to add just a list of single nodes.
But, please look at @100beans post, I faced with the problem too.
I download file from geofabrik https://download.geofabrik.de/europe/poland/malopolskie.html and use maven to make a db:
java -cp target/classes:target/dependency/* org.neo4j.gis.spatial.osm.OSMImporter new-osm-db malopolskie-latest.osm
And got:
malopolskie-latest.osm[98500842]: Completed load in 1592.819s
malopolskie-latest.osm[98500842]:       Imported nodes:  756.139s
malopolskie-latest.osm[98500842]:       Optimized index: 0.0s
malopolskie-latest.osm[98500842]:       Imported ways:   829.179s
malopolskie-latest.osm[98500842]:       Optimized index: 0.0s
malopolskie-latest.osm[98500842]:       Imported rels:   7.501s
malopolskie-latest.osm[98500842]: When processing the relations, there were 189606 missing members
Thu Jan 01 04:00:00 SAMT 1970: Found 12937072 nodes during 0s way creation: 
        changeset:      12937072/816s   (15836.981723365447 nodes/second)
Loaded 11296720 nodes
Loaded 1411075 ways
Loaded 10596 relations
malopolskie-latest.osm[98500842]: info | Elapsed time in seconds: 1592.82
Geometry statistics for 3 geometry types:
        Point: 605917
        LineString: 319703
        Polygon: 1091372
Tag statistics for 4 types:
...
malopolskie-latest.osm[98500842]: Re-indexing with GraphDatabaseService: community single [/data/alex/spatial/new-osm-db] (class: class org.neo4j.kernel.impl.factory.GraphDatabaseFacade)
Index[0]: info | Re-indexing elapsed time in seconds: 0.056
Geometry statistics for 0 geometry types:
=== Completed loading malopolskie-latest.osm in 1600.435 seconds ===
...Spatial queries doesn't work.

I've investigated that if I remove ' changeset="0" ' by replacing it to '', reindexing starts, but I got NullPointerException on line 225 of OSMImporter.java:
for ( Node proxy : findNodes.traverse( way ).nodes() )
{
Node node = proxy.getSingleRelationship(
>>> OSMRelation.NODE, Direction.OUTGOING ).getEndNode();
stats.addGeomStats( layer.addWay( node, true ) );
}

Note, that file from geofabrik comes with changeset="0" for each element.

**Comment by craigtaverner** [comment] 2018-08-05 11:30
I noticed that we fixed a bug a few months ago related to OSM files without changeset attributes. And one of the parts of that bug-fix is that previously we relied on a full changeset->way->node path to find things to index, but if the changesets were missing, we needed to look instead for way->node patterns to index. The bug you are reporting here seems to relate to that second option. So my suspicion is that this new bug is strongly related to the old one. Either the previous bug-fix did not cover sufficient cases, or it in fact uncovered a new bug. I need to find some time to test this out on the data files you are testing with. Hopefully in the next two weeks.

You mention above that you get a NPE on line 225, but the code you show looks more like line 275? See https://github.com/neo4j-contrib/spatial/blob/master/src/main/java/org/neo4j/gis/spatial/osm/OSMImporter.java#L275

Could you confirm. I noticed that that code is only activated if two conditions are true:

* You have no changesets
* You have turned on 'includePoints' which means index all points (as you noted this is normally off)

**Comment by craigtaverner** [comment] 2018-08-05 11:41
One possible NPE on line 275 would be that getSingleRelationship can return null, and then calling getEndNode() will cause the NPE. However the OSM data model requires all proxy nodes to have these relationships, so either the data model is broken (missing NODE relationships) or the findNodes traversal is finding nodes that are not proxies. Looking at the code I see nothing obviously wrong with it, so again I would need to find the time to actually debug this (cannot do it now, because I'm on a computer without the dev-environment necessary). If I have given you enough hints to fix it yourself, feel free to provide a PR and we can get it merged. Otherwise you'll need to wait for me to get the chance to fix it.

**Comment by Kubera2017** [comment] 2018-08-05 12:31
"One possible NPE on line 275 would be that getSingleRelationship can return null, and then calling getEndNode() will cause the NPE. However the OSM data model requires all proxy nodes to have these relationships, so either the data model is broken (missing NODE relationships) or the findNodes traversal is finding nodes that are not proxies."
- maybe it relies on:
"malopolskie-latest.osm[98500842]: When processing the relations, there were 189606 missing members"
But it happens with files from https://download.bbbike.org/osm/bbbike/Cracow/ too. So it brakes all usefullness of the plugin, need to find a solution.

**Comment by craigtaverner** [comment] 2018-08-06 22:00
@Kubera2017 - I've tested with the cracow data, and notice two issues:

* This is a large dataset, and the current OSMImporter is not very fast for such data. There is a much faster OSM importer I've been working on at https://github.com/neo4j-contrib/osm. That importer is much faster and can load much larger amounts of data (I tested with a dataset of a few hundred million nodes).
* When I cut out many of the nodes from Cracow to make a smaller dataset, I very quickly got the NPE that you see. It is occurring in a piece of code that is only active if there is no changeset attribute. This code breaks when the ways refer to nodes that do not exist (which happens when you manually edit files, and sometimes exists in OSM exports anyway).

What I notice here is that files with changeset attributes follow a different code path than files without. And the former code path does not support `includePoints` while the latter does. This is certainly a bug. To reduce the scope of the bug I've made two changes:

* Make the default for procedures to turn off `includePoints`, so only ways get indexed. This will mean that datasets with and without changesets will be indexed the same (only ways).
* Added error detection code so that if you do run with `includePoints` (for example, by using the command-line importer), it does not crash, but instead prints warnings.

I will try make a new release with this fix in it soon, for 3.4.x only. Hopefully everyone has upgraded to that version.

**Comment by craigtaverner** [comment] 2018-08-07 13:02
I've made a bugfix release at https://github.com/neo4j-contrib/spatial/releases/tag/0.25-neo4j-3.4.5

This fixes the main issue, I believe. Can you test it and see if it is sufficient for your solution, and if not, re-open this issue with new details, or make a new issue.

**Closed by craigtaverner** 2018-08-07 13:02 UTC
